### ISSUE TITLE
Are you going to update this?

### ISSUE THREAD

**Issue by Rufis01** [wildbillcat/KinectCam#1]
I wa interested in modifing this, but I have some problems getting it running. Are you gonna update this as you said?

**Comment by wildbillcat** [comment]
Should already work with the original Kinect and v1 sdk. No longer have a Kinect anymore so I can't check to see if something changed. What's the bug?

**Comment by aBaTaPbl4** [comment]
Hi, wildbillcat)
Actually, i can't make it work with kinect sdk 1.8. My system(Windows 10 x64 Pro) does not see the kinect as webcam in skype. It says, - no web cam detected.
For example tools from Developer Toolkit v1.8.0 works fine...
Could you assist me, please?

**Comment by Deledrius** [comment]
I'd like to work on updating this project to work with the current version of Windows, but there doesn't appear to be a license attached to the project's code.

**Comment by wildbillcat** [comment]
Would the mit license work?

**Comment by Deledrius** [comment]
The MIT License would suit the project well, I think.

**Comment by wildbillcat** [comment]
There you go. Enjoy the code!
